param(
  [string]$ScholarUserId = "D1ji84AAAAAJ",
  [string]$Language = "ru",
  [string]$OutputPath = "assets/js/scholar-stats.js"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# %%%%26.04.2026%%%%%%% Google Scholar stats sync
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptRoot
$outputFile = Join-Path $projectRoot $OutputPath

$headers = @{
  "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
  "Accept-Language" = "$Language,en;q=0.9"
}

function Invoke-ScholarRequest {
  param([string]$Url)

  $lastError = $null

  foreach ($attempt in 1..3) {
    try {
      $requestParams = @{
        Uri = $Url
        Headers = $headers
      }

      if ((Get-Command Invoke-WebRequest).Parameters.ContainsKey("UseBasicParsing")) {
        $requestParams.UseBasicParsing = $true
      }

      return (Invoke-WebRequest @requestParams).Content
    } catch {
      $lastError = $_
      if ($attempt -lt 3) {
        Start-Sleep -Seconds (2 * $attempt)
      }
    }
  }

  throw $lastError
}

$syncIsOptional = $env:SCHOLAR_SYNC_OPTIONAL -eq "true"

try {
  $profileUrl = "https://scholar.google.com/citations?user=$ScholarUserId&hl=$Language&cstart=0&pagesize=1000"
  $profileHtml = Invoke-ScholarRequest $profileUrl

  $metricMatches = [regex]::Matches($profileHtml, '<td class="gsc_rsb_std">([^<]+)</td>')
  if ($metricMatches.Count -lt 6) {
    throw "Could not parse Scholar metrics from $profileUrl"
  }

  $metricValues = @($metricMatches | ForEach-Object {
    [int](($_.Groups[1].Value -replace '[^\d]', ''))
  })

  $publicationCount = ([regex]::Matches($profileHtml, '<tr class="gsc_a_tr">')).Count
  if ($publicationCount -le 0) {
    throw "Could not parse publications from $profileUrl"
  }

  $coauthorsUrl = "https://scholar.google.com/citations?view_op=list_colleagues&hl=$Language&json=&user=$ScholarUserId&pagesize=1000"
  $coauthorsHtml = Invoke-ScholarRequest $coauthorsUrl
  $coauthorCount = ([regex]::Matches($coauthorsHtml, '<div class="gsc_ucoar gs_scl"')).Count

  $stats = [ordered]@{
    updatedAt = (Get-Date).ToUniversalTime().ToString("o")
    sourceUrl = "https://scholar.google.com/citations?user=$ScholarUserId&hl=$Language"
    metrics = [ordered]@{
      publications = $publicationCount
      citations = $metricValues[0]
      citations5y = $metricValues[1]
      hIndex = $metricValues[2]
      hIndex5y = $metricValues[3]
      i10Index = $metricValues[4]
      i10Index5y = $metricValues[5]
      coauthors = $coauthorCount
    }
  }

  $json = $stats | ConvertTo-Json -Depth 4
  $js = @(
    "// Auto-generated by scripts/update-scholar-stats.ps1",
    "window.SCHOLAR_STATS = $json;",
    ""
  ) -join [Environment]::NewLine

  [IO.Directory]::CreateDirectory((Split-Path -Parent $outputFile)) | Out-Null
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [IO.File]::WriteAllText($outputFile, $js, $utf8NoBom)
  # %%%%26.04.2026%%%%%%% Google Scholar stats sync

  Write-Host "Updated $outputFile"
  Write-Host ($stats.metrics | ConvertTo-Json -Compress)
} catch {
  if ($syncIsOptional -and (Test-Path $outputFile)) {
    Write-Warning "%%%%26.04.2026%%%%%%% Scholar sync skipped: $($_.Exception.Message)"
    Write-Warning "%%%%26.04.2026%%%%%%% Keeping existing snapshot at $outputFile"
    exit 0
  }

  throw
}
